# Generated by Django 5.2.1 on 2025-05-13 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_token',
        ),
    ]
