# Generated by Django 5.2.1 on 2025-05-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
